version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: 'mariadb:10.10.2'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: elect_manager
    ports:
      - '3306'
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
